// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FillName: typeof import('./src/components/account/FillName.vue')['default']
    ImgTo16: typeof import('./src/components/tool/ImgTo16.vue')['default']
    ImgToGray: typeof import('./src/components/tool/ImgToGray.vue')['default']
    ImgToStr: typeof import('./src/components/tool/ImgToStr.vue')['default']
    OpenRoom: typeof import('./src/components/account/OpenRoom.vue')['default']
    QrCode: typeof import('./src/components/account/QrCode.vue')['default']
    Room: typeof import('./src/components/account/Room.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareRoom: typeof import('./src/components/account/ShareRoom.vue')['default']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
