# 使用官方 Node.js 镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package.json package-lock.json ./

# 安装依赖
RUN npm ci

# 复制构建后的代码
COPY dist ./dist

# 暴露端口
EXPOSE 6015

# 启动应用
CMD ["node", "dist/main.js"] 